service: aws-python-facts
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: api.handler.hello
    events:
      - httpApi:
          path: /
          method: get
